/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.demo.bankaccount.avro.pojo;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BankAccount extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1063189084044042824L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BankAccount\",\"namespace\":\"io.confluent.demo.bankaccount.avro.pojo\",\"fields\":[{\"name\":\"oneof_type\",\"type\":[{\"type\":\"record\",\"name\":\"NewAccount\",\"fields\":[{\"name\":\"account_id\",\"type\":\"long\"},{\"name\":\"customer_name\",\"type\":\"string\"},{\"name\":\"customer_email\",\"type\":\"string\"},{\"name\":\"customer_address\",\"type\":\"string\"},{\"name\":\"account_creation_date\",\"type\":\"int\",\"logicalType\":\"date\"}]},{\"type\":\"record\",\"name\":\"Deposit\",\"fields\":[{\"name\":\"account_id\",\"type\":\"long\"},{\"name\":\"amount\",\"type\":\"double\"},{\"name\":\"deposit_date\",\"type\":\"int\",\"logicalType\":\"date\"}]},{\"type\":\"record\",\"name\":\"Withdrawal\",\"fields\":[{\"name\":\"account_id\",\"type\":\"long\"},{\"name\":\"amount\",\"type\":\"double\"},{\"name\":\"withdrawal_date\",\"type\":\"int\",\"logicalType\":\"date\"}]}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BankAccount> ENCODER =
      new BinaryMessageEncoder<BankAccount>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BankAccount> DECODER =
      new BinaryMessageDecoder<BankAccount>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BankAccount> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BankAccount> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BankAccount> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BankAccount>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BankAccount to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BankAccount from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BankAccount instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BankAccount fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.Object oneof_type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BankAccount() {}

  /**
   * All-args constructor.
   * @param oneof_type The new value for oneof_type
   */
  public BankAccount(java.lang.Object oneof_type) {
    this.oneof_type = oneof_type;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return oneof_type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: oneof_type = value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'oneof_type' field.
   * @return The value of the 'oneof_type' field.
   */
  public java.lang.Object getOneofType() {
    return oneof_type;
  }


  /**
   * Sets the value of the 'oneof_type' field.
   * @param value the value to set.
   */
  public void setOneofType(java.lang.Object value) {
    this.oneof_type = value;
  }

  /**
   * Creates a new BankAccount RecordBuilder.
   * @return A new BankAccount RecordBuilder
   */
  public static io.confluent.demo.bankaccount.avro.pojo.BankAccount.Builder newBuilder() {
    return new io.confluent.demo.bankaccount.avro.pojo.BankAccount.Builder();
  }

  /**
   * Creates a new BankAccount RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BankAccount RecordBuilder
   */
  public static io.confluent.demo.bankaccount.avro.pojo.BankAccount.Builder newBuilder(io.confluent.demo.bankaccount.avro.pojo.BankAccount.Builder other) {
    if (other == null) {
      return new io.confluent.demo.bankaccount.avro.pojo.BankAccount.Builder();
    } else {
      return new io.confluent.demo.bankaccount.avro.pojo.BankAccount.Builder(other);
    }
  }

  /**
   * Creates a new BankAccount RecordBuilder by copying an existing BankAccount instance.
   * @param other The existing instance to copy.
   * @return A new BankAccount RecordBuilder
   */
  public static io.confluent.demo.bankaccount.avro.pojo.BankAccount.Builder newBuilder(io.confluent.demo.bankaccount.avro.pojo.BankAccount other) {
    if (other == null) {
      return new io.confluent.demo.bankaccount.avro.pojo.BankAccount.Builder();
    } else {
      return new io.confluent.demo.bankaccount.avro.pojo.BankAccount.Builder(other);
    }
  }

  /**
   * RecordBuilder for BankAccount instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BankAccount>
    implements org.apache.avro.data.RecordBuilder<BankAccount> {

    private java.lang.Object oneof_type;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.demo.bankaccount.avro.pojo.BankAccount.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.oneof_type)) {
        this.oneof_type = data().deepCopy(fields()[0].schema(), other.oneof_type);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing BankAccount instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.demo.bankaccount.avro.pojo.BankAccount other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.oneof_type)) {
        this.oneof_type = data().deepCopy(fields()[0].schema(), other.oneof_type);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'oneof_type' field.
      * @return The value.
      */
    public java.lang.Object getOneofType() {
      return oneof_type;
    }


    /**
      * Sets the value of the 'oneof_type' field.
      * @param value The value of 'oneof_type'.
      * @return This builder.
      */
    public io.confluent.demo.bankaccount.avro.pojo.BankAccount.Builder setOneofType(java.lang.Object value) {
      validate(fields()[0], value);
      this.oneof_type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'oneof_type' field has been set.
      * @return True if the 'oneof_type' field has been set, false otherwise.
      */
    public boolean hasOneofType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'oneof_type' field.
      * @return This builder.
      */
    public io.confluent.demo.bankaccount.avro.pojo.BankAccount.Builder clearOneofType() {
      oneof_type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BankAccount build() {
      try {
        BankAccount record = new BankAccount();
        record.oneof_type = fieldSetFlags()[0] ? this.oneof_type :  defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BankAccount>
    WRITER$ = (org.apache.avro.io.DatumWriter<BankAccount>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BankAccount>
    READER$ = (org.apache.avro.io.DatumReader<BankAccount>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










