/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.demo.bankaccount.avro.pojo;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class NewAccount extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8171705644498803598L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NewAccount\",\"namespace\":\"io.confluent.demo.bankaccount.avro.pojo\",\"fields\":[{\"name\":\"account_id\",\"type\":\"long\"},{\"name\":\"customer_name\",\"type\":\"string\"},{\"name\":\"customer_email\",\"type\":\"string\"},{\"name\":\"customer_address\",\"type\":\"string\"},{\"name\":\"account_creation_date\",\"type\":\"long\",\"logicalType\":\"date\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<NewAccount> ENCODER =
      new BinaryMessageEncoder<NewAccount>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NewAccount> DECODER =
      new BinaryMessageDecoder<NewAccount>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<NewAccount> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<NewAccount> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<NewAccount> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<NewAccount>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this NewAccount to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a NewAccount from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a NewAccount instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static NewAccount fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long account_id;
  @Deprecated public java.lang.CharSequence customer_name;
  @Deprecated public java.lang.CharSequence customer_email;
  @Deprecated public java.lang.CharSequence customer_address;
  @Deprecated public long account_creation_date;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NewAccount() {}

  /**
   * All-args constructor.
   * @param account_id The new value for account_id
   * @param customer_name The new value for customer_name
   * @param customer_email The new value for customer_email
   * @param customer_address The new value for customer_address
   * @param account_creation_date The new value for account_creation_date
   */
  public NewAccount(java.lang.Long account_id, java.lang.CharSequence customer_name, java.lang.CharSequence customer_email, java.lang.CharSequence customer_address, java.lang.Long account_creation_date) {
    this.account_id = account_id;
    this.customer_name = customer_name;
    this.customer_email = customer_email;
    this.customer_address = customer_address;
    this.account_creation_date = account_creation_date;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return account_id;
    case 1: return customer_name;
    case 2: return customer_email;
    case 3: return customer_address;
    case 4: return account_creation_date;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: account_id = (java.lang.Long)value$; break;
    case 1: customer_name = (java.lang.CharSequence)value$; break;
    case 2: customer_email = (java.lang.CharSequence)value$; break;
    case 3: customer_address = (java.lang.CharSequence)value$; break;
    case 4: account_creation_date = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'account_id' field.
   * @return The value of the 'account_id' field.
   */
  public long getAccountId() {
    return account_id;
  }


  /**
   * Sets the value of the 'account_id' field.
   * @param value the value to set.
   */
  public void setAccountId(long value) {
    this.account_id = value;
  }

  /**
   * Gets the value of the 'customer_name' field.
   * @return The value of the 'customer_name' field.
   */
  public java.lang.CharSequence getCustomerName() {
    return customer_name;
  }


  /**
   * Sets the value of the 'customer_name' field.
   * @param value the value to set.
   */
  public void setCustomerName(java.lang.CharSequence value) {
    this.customer_name = value;
  }

  /**
   * Gets the value of the 'customer_email' field.
   * @return The value of the 'customer_email' field.
   */
  public java.lang.CharSequence getCustomerEmail() {
    return customer_email;
  }


  /**
   * Sets the value of the 'customer_email' field.
   * @param value the value to set.
   */
  public void setCustomerEmail(java.lang.CharSequence value) {
    this.customer_email = value;
  }

  /**
   * Gets the value of the 'customer_address' field.
   * @return The value of the 'customer_address' field.
   */
  public java.lang.CharSequence getCustomerAddress() {
    return customer_address;
  }


  /**
   * Sets the value of the 'customer_address' field.
   * @param value the value to set.
   */
  public void setCustomerAddress(java.lang.CharSequence value) {
    this.customer_address = value;
  }

  /**
   * Gets the value of the 'account_creation_date' field.
   * @return The value of the 'account_creation_date' field.
   */
  public long getAccountCreationDate() {
    return account_creation_date;
  }


  /**
   * Sets the value of the 'account_creation_date' field.
   * @param value the value to set.
   */
  public void setAccountCreationDate(long value) {
    this.account_creation_date = value;
  }

  /**
   * Creates a new NewAccount RecordBuilder.
   * @return A new NewAccount RecordBuilder
   */
  public static io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder newBuilder() {
    return new io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder();
  }

  /**
   * Creates a new NewAccount RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NewAccount RecordBuilder
   */
  public static io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder newBuilder(io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder other) {
    if (other == null) {
      return new io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder();
    } else {
      return new io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder(other);
    }
  }

  /**
   * Creates a new NewAccount RecordBuilder by copying an existing NewAccount instance.
   * @param other The existing instance to copy.
   * @return A new NewAccount RecordBuilder
   */
  public static io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder newBuilder(io.confluent.demo.bankaccount.avro.pojo.NewAccount other) {
    if (other == null) {
      return new io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder();
    } else {
      return new io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder(other);
    }
  }

  /**
   * RecordBuilder for NewAccount instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NewAccount>
    implements org.apache.avro.data.RecordBuilder<NewAccount> {

    private long account_id;
    private java.lang.CharSequence customer_name;
    private java.lang.CharSequence customer_email;
    private java.lang.CharSequence customer_address;
    private long account_creation_date;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.account_id)) {
        this.account_id = data().deepCopy(fields()[0].schema(), other.account_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.customer_name)) {
        this.customer_name = data().deepCopy(fields()[1].schema(), other.customer_name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.customer_email)) {
        this.customer_email = data().deepCopy(fields()[2].schema(), other.customer_email);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.customer_address)) {
        this.customer_address = data().deepCopy(fields()[3].schema(), other.customer_address);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.account_creation_date)) {
        this.account_creation_date = data().deepCopy(fields()[4].schema(), other.account_creation_date);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing NewAccount instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.demo.bankaccount.avro.pojo.NewAccount other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.account_id)) {
        this.account_id = data().deepCopy(fields()[0].schema(), other.account_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customer_name)) {
        this.customer_name = data().deepCopy(fields()[1].schema(), other.customer_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.customer_email)) {
        this.customer_email = data().deepCopy(fields()[2].schema(), other.customer_email);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.customer_address)) {
        this.customer_address = data().deepCopy(fields()[3].schema(), other.customer_address);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.account_creation_date)) {
        this.account_creation_date = data().deepCopy(fields()[4].schema(), other.account_creation_date);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'account_id' field.
      * @return The value.
      */
    public long getAccountId() {
      return account_id;
    }


    /**
      * Sets the value of the 'account_id' field.
      * @param value The value of 'account_id'.
      * @return This builder.
      */
    public io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder setAccountId(long value) {
      validate(fields()[0], value);
      this.account_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'account_id' field has been set.
      * @return True if the 'account_id' field has been set, false otherwise.
      */
    public boolean hasAccountId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'account_id' field.
      * @return This builder.
      */
    public io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder clearAccountId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'customer_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerName() {
      return customer_name;
    }


    /**
      * Sets the value of the 'customer_name' field.
      * @param value The value of 'customer_name'.
      * @return This builder.
      */
    public io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder setCustomerName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.customer_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'customer_name' field has been set.
      * @return True if the 'customer_name' field has been set, false otherwise.
      */
    public boolean hasCustomerName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'customer_name' field.
      * @return This builder.
      */
    public io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder clearCustomerName() {
      customer_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'customer_email' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerEmail() {
      return customer_email;
    }


    /**
      * Sets the value of the 'customer_email' field.
      * @param value The value of 'customer_email'.
      * @return This builder.
      */
    public io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder setCustomerEmail(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.customer_email = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'customer_email' field has been set.
      * @return True if the 'customer_email' field has been set, false otherwise.
      */
    public boolean hasCustomerEmail() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'customer_email' field.
      * @return This builder.
      */
    public io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder clearCustomerEmail() {
      customer_email = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'customer_address' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerAddress() {
      return customer_address;
    }


    /**
      * Sets the value of the 'customer_address' field.
      * @param value The value of 'customer_address'.
      * @return This builder.
      */
    public io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder setCustomerAddress(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.customer_address = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'customer_address' field has been set.
      * @return True if the 'customer_address' field has been set, false otherwise.
      */
    public boolean hasCustomerAddress() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'customer_address' field.
      * @return This builder.
      */
    public io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder clearCustomerAddress() {
      customer_address = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'account_creation_date' field.
      * @return The value.
      */
    public long getAccountCreationDate() {
      return account_creation_date;
    }


    /**
      * Sets the value of the 'account_creation_date' field.
      * @param value The value of 'account_creation_date'.
      * @return This builder.
      */
    public io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder setAccountCreationDate(long value) {
      validate(fields()[4], value);
      this.account_creation_date = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'account_creation_date' field has been set.
      * @return True if the 'account_creation_date' field has been set, false otherwise.
      */
    public boolean hasAccountCreationDate() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'account_creation_date' field.
      * @return This builder.
      */
    public io.confluent.demo.bankaccount.avro.pojo.NewAccount.Builder clearAccountCreationDate() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public NewAccount build() {
      try {
        NewAccount record = new NewAccount();
        record.account_id = fieldSetFlags()[0] ? this.account_id : (java.lang.Long) defaultValue(fields()[0]);
        record.customer_name = fieldSetFlags()[1] ? this.customer_name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.customer_email = fieldSetFlags()[2] ? this.customer_email : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.customer_address = fieldSetFlags()[3] ? this.customer_address : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.account_creation_date = fieldSetFlags()[4] ? this.account_creation_date : (java.lang.Long) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NewAccount>
    WRITER$ = (org.apache.avro.io.DatumWriter<NewAccount>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NewAccount>
    READER$ = (org.apache.avro.io.DatumReader<NewAccount>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.account_id);

    out.writeString(this.customer_name);

    out.writeString(this.customer_email);

    out.writeString(this.customer_address);

    out.writeLong(this.account_creation_date);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.account_id = in.readLong();

      this.customer_name = in.readString(this.customer_name instanceof Utf8 ? (Utf8)this.customer_name : null);

      this.customer_email = in.readString(this.customer_email instanceof Utf8 ? (Utf8)this.customer_email : null);

      this.customer_address = in.readString(this.customer_address instanceof Utf8 ? (Utf8)this.customer_address : null);

      this.account_creation_date = in.readLong();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.account_id = in.readLong();
          break;

        case 1:
          this.customer_name = in.readString(this.customer_name instanceof Utf8 ? (Utf8)this.customer_name : null);
          break;

        case 2:
          this.customer_email = in.readString(this.customer_email instanceof Utf8 ? (Utf8)this.customer_email : null);
          break;

        case 3:
          this.customer_address = in.readString(this.customer_address instanceof Utf8 ? (Utf8)this.customer_address : null);
          break;

        case 4:
          this.account_creation_date = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










