/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.demo.bankaccount.avro.pojo;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Random extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6380884626506895467L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Random\",\"namespace\":\"io.confluent.demo.bankaccount.avro.pojo\",\"fields\":[{\"name\":\"random_1\",\"type\":\"string\"},{\"name\":\"random_2\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Random> ENCODER =
      new BinaryMessageEncoder<Random>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Random> DECODER =
      new BinaryMessageDecoder<Random>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Random> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Random> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Random> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Random>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Random to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Random from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Random instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Random fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence random_1;
  @Deprecated public java.lang.CharSequence random_2;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Random() {}

  /**
   * All-args constructor.
   * @param random_1 The new value for random_1
   * @param random_2 The new value for random_2
   */
  public Random(java.lang.CharSequence random_1, java.lang.CharSequence random_2) {
    this.random_1 = random_1;
    this.random_2 = random_2;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return random_1;
    case 1: return random_2;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: random_1 = (java.lang.CharSequence)value$; break;
    case 1: random_2 = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'random_1' field.
   * @return The value of the 'random_1' field.
   */
  public java.lang.CharSequence getRandom1() {
    return random_1;
  }


  /**
   * Sets the value of the 'random_1' field.
   * @param value the value to set.
   */
  public void setRandom1(java.lang.CharSequence value) {
    this.random_1 = value;
  }

  /**
   * Gets the value of the 'random_2' field.
   * @return The value of the 'random_2' field.
   */
  public java.lang.CharSequence getRandom2() {
    return random_2;
  }


  /**
   * Sets the value of the 'random_2' field.
   * @param value the value to set.
   */
  public void setRandom2(java.lang.CharSequence value) {
    this.random_2 = value;
  }

  /**
   * Creates a new Random RecordBuilder.
   * @return A new Random RecordBuilder
   */
  public static io.confluent.demo.bankaccount.avro.pojo.Random.Builder newBuilder() {
    return new io.confluent.demo.bankaccount.avro.pojo.Random.Builder();
  }

  /**
   * Creates a new Random RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Random RecordBuilder
   */
  public static io.confluent.demo.bankaccount.avro.pojo.Random.Builder newBuilder(io.confluent.demo.bankaccount.avro.pojo.Random.Builder other) {
    if (other == null) {
      return new io.confluent.demo.bankaccount.avro.pojo.Random.Builder();
    } else {
      return new io.confluent.demo.bankaccount.avro.pojo.Random.Builder(other);
    }
  }

  /**
   * Creates a new Random RecordBuilder by copying an existing Random instance.
   * @param other The existing instance to copy.
   * @return A new Random RecordBuilder
   */
  public static io.confluent.demo.bankaccount.avro.pojo.Random.Builder newBuilder(io.confluent.demo.bankaccount.avro.pojo.Random other) {
    if (other == null) {
      return new io.confluent.demo.bankaccount.avro.pojo.Random.Builder();
    } else {
      return new io.confluent.demo.bankaccount.avro.pojo.Random.Builder(other);
    }
  }

  /**
   * RecordBuilder for Random instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Random>
    implements org.apache.avro.data.RecordBuilder<Random> {

    private java.lang.CharSequence random_1;
    private java.lang.CharSequence random_2;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.demo.bankaccount.avro.pojo.Random.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.random_1)) {
        this.random_1 = data().deepCopy(fields()[0].schema(), other.random_1);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.random_2)) {
        this.random_2 = data().deepCopy(fields()[1].schema(), other.random_2);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Random instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.demo.bankaccount.avro.pojo.Random other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.random_1)) {
        this.random_1 = data().deepCopy(fields()[0].schema(), other.random_1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.random_2)) {
        this.random_2 = data().deepCopy(fields()[1].schema(), other.random_2);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'random_1' field.
      * @return The value.
      */
    public java.lang.CharSequence getRandom1() {
      return random_1;
    }


    /**
      * Sets the value of the 'random_1' field.
      * @param value The value of 'random_1'.
      * @return This builder.
      */
    public io.confluent.demo.bankaccount.avro.pojo.Random.Builder setRandom1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.random_1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'random_1' field has been set.
      * @return True if the 'random_1' field has been set, false otherwise.
      */
    public boolean hasRandom1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'random_1' field.
      * @return This builder.
      */
    public io.confluent.demo.bankaccount.avro.pojo.Random.Builder clearRandom1() {
      random_1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'random_2' field.
      * @return The value.
      */
    public java.lang.CharSequence getRandom2() {
      return random_2;
    }


    /**
      * Sets the value of the 'random_2' field.
      * @param value The value of 'random_2'.
      * @return This builder.
      */
    public io.confluent.demo.bankaccount.avro.pojo.Random.Builder setRandom2(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.random_2 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'random_2' field has been set.
      * @return True if the 'random_2' field has been set, false otherwise.
      */
    public boolean hasRandom2() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'random_2' field.
      * @return This builder.
      */
    public io.confluent.demo.bankaccount.avro.pojo.Random.Builder clearRandom2() {
      random_2 = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Random build() {
      try {
        Random record = new Random();
        record.random_1 = fieldSetFlags()[0] ? this.random_1 : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.random_2 = fieldSetFlags()[1] ? this.random_2 : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Random>
    WRITER$ = (org.apache.avro.io.DatumWriter<Random>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Random>
    READER$ = (org.apache.avro.io.DatumReader<Random>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.random_1);

    out.writeString(this.random_2);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.random_1 = in.readString(this.random_1 instanceof Utf8 ? (Utf8)this.random_1 : null);

      this.random_2 = in.readString(this.random_2 instanceof Utf8 ? (Utf8)this.random_2 : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.random_1 = in.readString(this.random_1 instanceof Utf8 ? (Utf8)this.random_1 : null);
          break;

        case 1:
          this.random_2 = in.readString(this.random_2 instanceof Utf8 ? (Utf8)this.random_2 : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










