/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.demo.orders.avro.pojo;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Product extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2380804772669061810L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Product\",\"namespace\":\"io.confluent.demo.orders.avro.pojo\",\"fields\":[{\"name\":\"product_id\",\"type\":\"long\"},{\"name\":\"product_name\",\"type\":\"string\"},{\"name\":\"product_price\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Product> ENCODER =
      new BinaryMessageEncoder<Product>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Product> DECODER =
      new BinaryMessageDecoder<Product>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Product> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Product> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Product> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Product>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Product to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Product from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Product instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Product fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long product_id;
  @Deprecated public java.lang.CharSequence product_name;
  @Deprecated public double product_price;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Product() {}

  /**
   * All-args constructor.
   * @param product_id The new value for product_id
   * @param product_name The new value for product_name
   * @param product_price The new value for product_price
   */
  public Product(java.lang.Long product_id, java.lang.CharSequence product_name, java.lang.Double product_price) {
    this.product_id = product_id;
    this.product_name = product_name;
    this.product_price = product_price;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return product_id;
    case 1: return product_name;
    case 2: return product_price;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: product_id = (java.lang.Long)value$; break;
    case 1: product_name = (java.lang.CharSequence)value$; break;
    case 2: product_price = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'product_id' field.
   * @return The value of the 'product_id' field.
   */
  public long getProductId() {
    return product_id;
  }


  /**
   * Sets the value of the 'product_id' field.
   * @param value the value to set.
   */
  public void setProductId(long value) {
    this.product_id = value;
  }

  /**
   * Gets the value of the 'product_name' field.
   * @return The value of the 'product_name' field.
   */
  public java.lang.CharSequence getProductName() {
    return product_name;
  }


  /**
   * Sets the value of the 'product_name' field.
   * @param value the value to set.
   */
  public void setProductName(java.lang.CharSequence value) {
    this.product_name = value;
  }

  /**
   * Gets the value of the 'product_price' field.
   * @return The value of the 'product_price' field.
   */
  public double getProductPrice() {
    return product_price;
  }


  /**
   * Sets the value of the 'product_price' field.
   * @param value the value to set.
   */
  public void setProductPrice(double value) {
    this.product_price = value;
  }

  /**
   * Creates a new Product RecordBuilder.
   * @return A new Product RecordBuilder
   */
  public static io.confluent.demo.orders.avro.pojo.Product.Builder newBuilder() {
    return new io.confluent.demo.orders.avro.pojo.Product.Builder();
  }

  /**
   * Creates a new Product RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Product RecordBuilder
   */
  public static io.confluent.demo.orders.avro.pojo.Product.Builder newBuilder(io.confluent.demo.orders.avro.pojo.Product.Builder other) {
    if (other == null) {
      return new io.confluent.demo.orders.avro.pojo.Product.Builder();
    } else {
      return new io.confluent.demo.orders.avro.pojo.Product.Builder(other);
    }
  }

  /**
   * Creates a new Product RecordBuilder by copying an existing Product instance.
   * @param other The existing instance to copy.
   * @return A new Product RecordBuilder
   */
  public static io.confluent.demo.orders.avro.pojo.Product.Builder newBuilder(io.confluent.demo.orders.avro.pojo.Product other) {
    if (other == null) {
      return new io.confluent.demo.orders.avro.pojo.Product.Builder();
    } else {
      return new io.confluent.demo.orders.avro.pojo.Product.Builder(other);
    }
  }

  /**
   * RecordBuilder for Product instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Product>
    implements org.apache.avro.data.RecordBuilder<Product> {

    private long product_id;
    private java.lang.CharSequence product_name;
    private double product_price;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.demo.orders.avro.pojo.Product.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.product_id)) {
        this.product_id = data().deepCopy(fields()[0].schema(), other.product_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.product_name)) {
        this.product_name = data().deepCopy(fields()[1].schema(), other.product_name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.product_price)) {
        this.product_price = data().deepCopy(fields()[2].schema(), other.product_price);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Product instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.demo.orders.avro.pojo.Product other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.product_id)) {
        this.product_id = data().deepCopy(fields()[0].schema(), other.product_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.product_name)) {
        this.product_name = data().deepCopy(fields()[1].schema(), other.product_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.product_price)) {
        this.product_price = data().deepCopy(fields()[2].schema(), other.product_price);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'product_id' field.
      * @return The value.
      */
    public long getProductId() {
      return product_id;
    }


    /**
      * Sets the value of the 'product_id' field.
      * @param value The value of 'product_id'.
      * @return This builder.
      */
    public io.confluent.demo.orders.avro.pojo.Product.Builder setProductId(long value) {
      validate(fields()[0], value);
      this.product_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'product_id' field has been set.
      * @return True if the 'product_id' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'product_id' field.
      * @return This builder.
      */
    public io.confluent.demo.orders.avro.pojo.Product.Builder clearProductId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'product_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductName() {
      return product_name;
    }


    /**
      * Sets the value of the 'product_name' field.
      * @param value The value of 'product_name'.
      * @return This builder.
      */
    public io.confluent.demo.orders.avro.pojo.Product.Builder setProductName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.product_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'product_name' field has been set.
      * @return True if the 'product_name' field has been set, false otherwise.
      */
    public boolean hasProductName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'product_name' field.
      * @return This builder.
      */
    public io.confluent.demo.orders.avro.pojo.Product.Builder clearProductName() {
      product_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'product_price' field.
      * @return The value.
      */
    public double getProductPrice() {
      return product_price;
    }


    /**
      * Sets the value of the 'product_price' field.
      * @param value The value of 'product_price'.
      * @return This builder.
      */
    public io.confluent.demo.orders.avro.pojo.Product.Builder setProductPrice(double value) {
      validate(fields()[2], value);
      this.product_price = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'product_price' field has been set.
      * @return True if the 'product_price' field has been set, false otherwise.
      */
    public boolean hasProductPrice() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'product_price' field.
      * @return This builder.
      */
    public io.confluent.demo.orders.avro.pojo.Product.Builder clearProductPrice() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Product build() {
      try {
        Product record = new Product();
        record.product_id = fieldSetFlags()[0] ? this.product_id : (java.lang.Long) defaultValue(fields()[0]);
        record.product_name = fieldSetFlags()[1] ? this.product_name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.product_price = fieldSetFlags()[2] ? this.product_price : (java.lang.Double) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Product>
    WRITER$ = (org.apache.avro.io.DatumWriter<Product>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Product>
    READER$ = (org.apache.avro.io.DatumReader<Product>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.product_id);

    out.writeString(this.product_name);

    out.writeDouble(this.product_price);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.product_id = in.readLong();

      this.product_name = in.readString(this.product_name instanceof Utf8 ? (Utf8)this.product_name : null);

      this.product_price = in.readDouble();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.product_id = in.readLong();
          break;

        case 1:
          this.product_name = in.readString(this.product_name instanceof Utf8 ? (Utf8)this.product_name : null);
          break;

        case 2:
          this.product_price = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










